apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-service-account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::004556044728:role/NginxServiceAccountRole
  namespace: nginx
  labels:
    app: nginx
    component: main
    env: prod
    tier: frontend